port: 8001

title: "Ethan"
author: "Ethan"
url: "https://ethan.link/"
description: "Hey, I’m Ethan. I like building beautiful software that helps people be more productive and improve their lives."

plugins:
  - jekyll-feed
  - jekyll-json-feed
  - jekyll-sitemap # leave at the end

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      rawname: post
      permalink: /blog/:title/

sass:
  style: compressed
