title:            Booligoosh
tagline:          ''
description:      ''
url:              
baseurl:          ''

email:            booligoosh@optusnet.com.au
newsletter:       'https://codetheweb.blog/newsletter/' # old: https://eepurl.com/bz0PTD

author:
  name:           'Booligoosh'
  url:            https://booligoosh.github.io/

description:      'The portfolio of Booligoosh - Graphic Designer, Programmer & Tech Enthusiast.'

paginate:         5

img: '/' # always end in /

gems:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-feed
  - jekyll-press
  - github-pages
  - jekyll-sitemap # leave at the end

contact:
  stackoverflow: 'https://stackoverflow.com/users/5374560/booligoosh'
  github: 'https://github.com/Booligoosh/'
  behance: 'https://www.behance.net/Booligoosh'
  dribble: 'https://dribbble.com/Booligoosh'
  scratch: 'https://scratch.mit.edu/users/Booligoosh/'
  codecademy: 'https://www.codecademy.com/Booligoosh'
  codingame: 'https://www.codingame.com/profile/1f7c0a954e65b4c68398cdf59a5fb7b56803941'



collections:
  coding:
    output: false
  scratch:
    output: false
  photography:
    output: false
